name: First Workflow
 on:
   push:
     brench:
       - main:
job:
  example-job:
    run-on: ubuntu-latest
    stepes:
      - name: print a welcome massege
        run: echo "Welcome to my firsrt GitHub Actions Workflow!"

      - name: Checkout reository 
        uses: actions/checkout@v6.0.1 
      - name: List reopsitory files 
        run: ls -la
